// Code generated by MockGen. DO NOT EDIT.
// Source: ./fast_node.go

// Package mock_iavl is a generated GoMock package.
package iavl

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNode is a mock of Node interface.
type MockNode struct {
	ctrl     *gomock.Controller
	recorder *MockNodeMockRecorder
}

// MockNodeMockRecorder is the mock recorder for MockNode.
type MockNodeMockRecorder struct {
	mock *MockNode
}

// NewMockNode creates a new mock instance.
func NewMockNode(ctrl *gomock.Controller) *MockNode {
	mock := &MockNode{ctrl: ctrl}
	mock.recorder = &MockNodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNode) EXPECT() *MockNodeMockRecorder {
	return m.recorder
}

// encodedSize mocks base method.
func (m *MockNode) EncodedSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodedSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// encodedSize indicates an expected call of encodedSize.
func (mr *MockNodeMockRecorder) encodedSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodedSize", reflect.TypeOf((*MockNode)(nil).EncodedSize))
}

// getKey mocks base method.
func (m *MockNode) GetKey() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKey")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// getKey indicates an expected call of getKey.
func (mr *MockNodeMockRecorder) getKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKey", reflect.TypeOf((*MockNode)(nil).GetKey))
}

// getValue mocks base method.
func (m *MockNode) GetValue() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// getValue indicates an expected call of getValue.
func (mr *MockNodeMockRecorder) getValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockNode)(nil).GetValue))
}

// getVersion mocks base method.
func (m *MockNode) GetVersion() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion")
	ret0, _ := ret[0].(int64)
	return ret0
}

// getVersion indicates an expected call of getVersion.
func (mr *MockNodeMockRecorder) getVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockNode)(nil).GetVersion))
}

// setKey mocks base method.
func (m *MockNode) SetKey(key []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetKey", key)
}

// setKey indicates an expected call of setKey.
func (mr *MockNodeMockRecorder) setKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKey", reflect.TypeOf((*MockNode)(nil).SetKey), key)
}

// writeBytes mocks base method.
func (m *MockNode) WriteBytes(w io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBytes", w)
	ret0, _ := ret[0].(error)
	return ret0
}

// writeBytes indicates an expected call of writeBytes.
func (mr *MockNodeMockRecorder) writeBytes(w interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBytes", reflect.TypeOf((*MockNode)(nil).WriteBytes), w)
}
